import { AKeyFrame } from "../../engine/definitions.ts";
import { v2, Vec2 } from "../../engine/geometry.ts";
import { Definitions,Definition } from "../../engine/mod.ts"
import { DeepPartial, mergeDeep } from "../../engine/utils.ts";
import { DefaultFistRig, ItemQuality } from "../../others/item.ts";
import { Boosts, BoostType } from "../player/boosts.ts";
import { SideEffect, SideEffectType } from "../player/effects.ts";
import { InventoryItemType } from "../utils.ts";

export enum ConsumibleCondition{
    UnfullHealth,
    UnfullExtra
}
export const ConsumiblesAnimations={
    drinking:(frame:string="yellow_soda",time:number=2,hotspot?:Vec2)=>[
        {
            actions:[
                {
                    type:"sprite",
                    fuser:"weapon",
                    image:frame,
                    visible:true,
                    scale:1.1,
                    rotation:-0.2,
                    hotspot:hotspot??v2.new(0.5,.5),
                    zIndex:6,
                    position:DefaultFistRig.right!.position
                },
                {
                    ...DefaultFistRig.left!,
                    visible:true,
                    type:"sprite",
                    fuser:"left_arm",
                },
                {
                    ...DefaultFistRig.right!,
                    visible:true,   
                    type:"sprite",
                    fuser:"right_arm",
                },
            ],
            time:0
        },
        {
            actions:[
                {
                    type:"tween",
                    fuser:"weapon",
                    to:{
                        rotation:-1.570796,
                        position:v2.new(.46,0)
                    }
                },
                {
                    type:"tween",
                    fuser:"right_arm",
                    to:{
                        rotation:DefaultFistRig.right!.rotation-0.4,
                        position:v2.new(DefaultFistRig.right!.position.x,DefaultFistRig.right!.position.y-0.2)
                    }
                }
            ],
            time:0.5
        }
    ]
}satisfies Record<string,()=>AKeyFrame[]>
export interface ConsumibleDef extends Definition{
    side_effects:SideEffect[]
    quality:ItemQuality
    use_delay:number
    condition?:ConsumibleCondition[]
    frame?:{
        using_particle:string
    }
    sounds?:{
        using?:string
    }
    boost_type?:BoostType
    drink?:boolean
    animation?:AKeyFrame[]
    item_type?:InventoryItemType.consumible
}
export const Consumibles=new Definitions<ConsumibleDef,{}>((i)=>{
    i.item_type=InventoryItemType.consumible
})
export function CreateSoda(color:string,boost_type:BoostType,max?:number,item:DeepPartial<ConsumibleDef>={}):ConsumibleDef{
    return mergeDeep({
        idString:color+"_soda",
        side_effects:[
            {
                type:SideEffectType.Heal,
                boost:{
                    amount:25,
                    max,
                    def:Boosts[boost_type]
                }
            }
        ],
        use_delay:2.65,
        quality:ItemQuality.Uncommon,
        condition:[ConsumibleCondition.UnfullExtra],
        animation:ConsumiblesAnimations.drinking(color+"_soda",2.5),
        drink:true,
        boost_type:boost_type,
        sounds:{
            using:"using_soda"
        }
    },item)
}
Consumibles.insert(
    {
        idString:"bandage",
        side_effects:[
            {
                type:SideEffectType.Heal,
                health:{
                    amount:20,
                    max:0.75
                }
            }
        ],
        use_delay:3,
        quality:ItemQuality.Uncommon,
        condition:[ConsumibleCondition.UnfullHealth],
        frame:{
            using_particle:"healing_particle"
        }
    },
    {
        idString:"medikit",
        side_effects:[
            {
                type:SideEffectType.Heal,
                health:{
                    amount:100,
                }
            }
        ],
        use_delay:5.5,
        quality:ItemQuality.Uncommon,
        condition:[ConsumibleCondition.UnfullHealth]
    },

    //Adrenaline
    CreateSoda("yellow",BoostType.Adrenaline),
    {
        idString:"inhaler",
        side_effects:[
            {
                type:SideEffectType.Heal,
                boost:{
                    amount:50,
                    def:Boosts[BoostType.Adrenaline]
                }
            }
        ],
        use_delay:4.5,
        quality:ItemQuality.Uncommon,
        condition:[ConsumibleCondition.UnfullExtra],
        boost_type:BoostType.Adrenaline
    },
    {
        idString:"yellow_pills",
        side_effects:[
            {
                type:SideEffectType.Heal,
                boost:{
                    amount:100,
                    def:Boosts[BoostType.Adrenaline]
                }
            }
        ],
        use_delay:6,
        quality:ItemQuality.Rare,
        condition:[ConsumibleCondition.UnfullExtra],
        boost_type:BoostType.Adrenaline,
        sounds:{
            using:"using_pills"
        }
    },

    //Shield
    CreateSoda("blue",BoostType.Shield,0.5),
    {
        idString:"blue_potion",
        side_effects:[
            {
                type:SideEffectType.Heal,
                boost:{
                    amount:50,
                    def:Boosts[BoostType.Shield]
                }
            }
        ],
        use_delay:4.5,
        quality:ItemQuality.Rare,
        condition:[ConsumibleCondition.UnfullExtra],
        sounds:{
            using:"using_potion"
        },
        animation:ConsumiblesAnimations.drinking("blue_potion",4.5,v2.new(0.5,0.35)),
        drink:true,
        boost_type:BoostType.Shield
    },
    {
        idString:"blue_pills",
        side_effects:[
            {
                type:SideEffectType.Heal,
                boost:{
                    amount:100,
                    def:Boosts[BoostType.Shield]
                }
            }
        ],
        use_delay:6,
        quality:ItemQuality.Epic,
        condition:[ConsumibleCondition.UnfullExtra],
        boost_type:BoostType.Shield,
        sounds:{
            using:"using_pills"
        }
    },
    //Mana
    CreateSoda("purple",BoostType.Mana),
    {
        idString:"purple_potion",
        side_effects:[
            {
                type:SideEffectType.Heal,
                boost:{
                    amount:50,
                    def:Boosts[BoostType.Mana]
                }
            }
        ],
        use_delay:4.5,
        quality:ItemQuality.Epic,
        condition:[ConsumibleCondition.UnfullExtra],
        sounds:{
            using:"using_potion"
        },
        animation:ConsumiblesAnimations.drinking("purple_potion",4.5,v2.new(0.5,0.35)),
        drink:true,
        boost_type:BoostType.Mana
    },
    {
        idString:"purple_pills",
        side_effects:[
            {
                type:SideEffectType.Heal,
                boost:{
                    amount:100,
                    def:Boosts[BoostType.Mana]
                }
            }
        ],
        use_delay:4.5,
        quality:ItemQuality.Legendary,
        condition:[ConsumibleCondition.UnfullExtra],
        boost_type:BoostType.Mana,
        sounds:{
            using:"using_pills"
        }
    },
    //Addiction
    CreateSoda("red",BoostType.Addiction),
    {
        idString:"small_red_crystal",
        use_delay:1.5,
        side_effects:[
            {
                type:SideEffectType.Heal,
                boost:{
                    amount:25,
                    max:.5,
                    def:Boosts[BoostType.Addiction]
                }
            }
        ],
        quality:ItemQuality.Epic,
        condition:[ConsumibleCondition.UnfullExtra],
        animation:ConsumiblesAnimations.drinking("small_red_crystal",1.4),
        boost_type:BoostType.Addiction
    },
    {
        idString:"red_crystal",
        use_delay:3,
        side_effects:[
            {
                type:SideEffectType.Heal,
                boost:{
                    amount:50,
                    def:Boosts[BoostType.Addiction]
                }
            }
        ],
        quality:ItemQuality.Epic,
        condition:[ConsumibleCondition.UnfullExtra],
        animation:ConsumiblesAnimations.drinking("red_crystal",2.9),
        boost_type:BoostType.Addiction
    },
    {
        idString:"red_pills",
        side_effects:[
            {
                type:SideEffectType.Heal,
                boost:{
                    amount:100,
                    def:Boosts[BoostType.Addiction]
                }
            }
        ],
        use_delay:4.5,
        quality:ItemQuality.Legendary,
        condition:[ConsumibleCondition.UnfullExtra],
        boost_type:BoostType.Addiction,
        sounds:{
            using:"using_pills"
        }
    },
    //Misc
    {
        idString:"pocket_portal",
        use_delay:1.5,
        side_effects:[
            {
                type:SideEffectType.Parachute
            }
        ],
        quality:ItemQuality.Mythic,
        boost_type:BoostType.Mana
    },
)