import { v2, Vec2 } from "../../engine/geometry.ts";
import { Definitions,Definition } from "../../engine/mod.ts";
import { FistRig,WeaponsArmRig,WeaponsRig, ItemQuality, tracers, WeaponRig } from "../../others/item.ts";
import { type BulletDef, GameItem, InventoryItemType } from "../utils.ts";
export enum FireMode{
    Auto,
    Single
}
export interface GasParticle{
    count:number
    size:{
        min:number
        max:number
    }
    speed:{
        min:number
        max:number
    }
    life_time:number
    direction_variation:number
}
export enum GunClasses{
    Shotgun,
    Sniper,
    Automatic,
    SMG,
    Magic
}
export interface MuzzleFlash{
    sprite:string
}
export const MuzzleFlash={
    normal:{
        sprite:"muzzle_flash_1",
    }
}
export interface GunDef extends Definition{
    bullet?:{
        def:BulletDef
        count?:number
    }
    projectile?:{
        def:string
        count?:number
        angular_speed?:number
        speed?:number
    }
    mana_consume?:number
    ammoSpawnAmount?:number
    ammoSpawn?:string
    fireDelay:number
    switchDelay?:number
    spread?:number
    lenght:number
    jitterRadius?:number
    fireMode?:FireMode
    speed_mod?:number
    size:number
    ammoType:string
    class:GunClasses
    quality:ItemQuality
    muzzleFlash?:MuzzleFlash
    reload?:{
        capacity:number
        delay:number
        shotsPerReload?:number
        reload_alt?:{
            delay:number
            shotsPerReload?:number
        }
    }
    recoil?:{
        duration:number
        speed:number
    }
    arms?:FistRig
    image?:WeaponRig
    caseParticle?:{
        position:Vec2
        at_begin?:boolean
        frame?:string
    }
    gasParticles?:GasParticle
}

export const Guns=new Definitions<GunDef,GameItem>((g)=>{
    g.item_type=InventoryItemType.gun
})

export const GasParticles={
    shotgun:{
        count:7,
        size:{
            min:0.5,
            max:1.2
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.9,
        direction_variation:0.4
    } satisfies GasParticle,
    sniper:{
        count:8,
        size:{
            min:0.6,
            max:1.4
        },
        speed:{
            min:1,
            max:2
        },
        life_time:1.1,
        direction_variation:0.43
    } satisfies GasParticle,
    automatic:{
        count:1,
        size:{
            min:0.8,
            max:1
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.7,
        direction_variation:0.2
    } satisfies GasParticle
}

Guns.insert(
    {
        idString:"ak47",
        fireDelay:0.1,
        switchDelay:0.6,
        spread:5,
        lenght:1.2,
        size:4,
        ammoType:"762mm",
        ammoSpawnAmount:90,
        class:GunClasses.Automatic,
        quality:ItemQuality.Rare,
        bullet:{
            def:{
                damage:10,
                radius:0.014,
                range:170,
                speed:40,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:2.5,
            capacity:30
        },
        recoil:{
            duration:0.12,
            speed:0.75
        },
        speed_mod:0.97,
        gasParticles:GasParticles.automatic,
        muzzleFlash:MuzzleFlash.normal,
        arms:WeaponsArmRig[0],
        image:WeaponsRig[0]
    },
    {
        idString:"ar15",
        fireDelay:0.12,
        switchDelay:0.7,
        spread:2,
        lenght:0.7,
        size:4,
        ammoType:"556mm",
        ammoSpawnAmount:90,
        class:GunClasses.Automatic,
        quality:ItemQuality.Rare,
        bullet:{
            def:{
                damage:9.8,
                radius:0.014,
                range:190,
                falloff:0.7,
                speed:42,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:2.5,
            capacity:30
        },
        recoil:{
            duration:0.14,
            speed:0.75
        },
        speed_mod:0.95,
        gasParticles:GasParticles.automatic
    },
    {
        idString:"mp5",
        fireDelay:0.09,
        switchDelay:0.7,
        spread:3,
        lenght:0.87,
        size:4,
        ammoType:"9mm",
        ammoSpawnAmount:96,
        class:GunClasses.Automatic,
        quality:ItemQuality.Uncommon,
        bullet:{
            def:{
                damage:8,
                radius:0.014,
                range:160,
                falloff:0.9,
                speed:37,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:2,
            capacity:32
        },
        recoil:{
            duration:0.11,
            speed:0.8
        },
        speed_mod:1,
        gasParticles:GasParticles.automatic,
        muzzleFlash:MuzzleFlash.normal,
        arms:WeaponsArmRig[2],
        image:{
            position:v2.new(0.5,0.0),
            rotation:0
        },
    },
    {
        idString:"vector",
        fireDelay:0.04,
        switchDelay:0.7,
        spread:1,
        lenght:0.68,
        size:4,
        ammoType:"9mm",
        ammoSpawnAmount:99,
        class:GunClasses.Automatic,
        quality:ItemQuality.Mythic,
        bullet:{
            def:{
                damage:5,
                radius:0.014,
                range:60,
                speed:34,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:1.7,
            capacity:33
        },
        recoil:{
            duration:0.07,
            speed:0.77
        },
        speed_mod:1,
        gasParticles:GasParticles.automatic
    },
    
    {
        idString:"uzi",
        fireDelay:0.04,
        switchDelay:0.7,
        spread:9,
        lenght:0.68,
        size:4,
        ammoType:"9mm",
        ammoSpawnAmount:96,
        class:GunClasses.Automatic,
        quality:ItemQuality.Rare,
        bullet:{
            def:{
                damage:5,
                radius:0.014,
                range:35,
                speed:34,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:1.7,
            capacity:32
        },
        recoil:{
            duration:0.07,
            speed:0.77
        },
        speed_mod:1,
        gasParticles:GasParticles.automatic
    },
    {
        idString:"kar98k",
        fireDelay:1.1,
        spread:0.4,
        lenght:1.26,
        size:4.5,
        ammoType:"762mm",
        ammoSpawnAmount:20,
        fireMode:FireMode.Single,
        class:GunClasses.Sniper,
        quality:ItemQuality.Mythic,
        bullet:{
            def:{
                damage:44,
                radius:0.02,
                range:210,
                falloff:0.8,
                criticalMult:1.1,
                speed:50,
                tracer:tracers.large
            }
        },
        reload:{
            delay:0.9,
            capacity:5,
            shotsPerReload:1,
            reload_alt:{
                delay:2.7,
            }
        },
        recoil:{
            duration:1.25,
            speed:0.4
        },
        speed_mod:0.95,
        arms:WeaponsArmRig[1],
        image:{
            position:v2.new(0.6,0.04),
            rotation:0
        },
        gasParticles:GasParticles.sniper,
        muzzleFlash:MuzzleFlash.normal,
        caseParticle:{
            position:v2.new(0.6,0.3)
        }
    },
    {
        idString:"awp",
        fireDelay:1.1,
        spread:0.5,
        lenght:0.9,
        size:6,
        ammoType:"762mm",
        fireMode:FireMode.Single,
        class:GunClasses.Sniper,
        quality:ItemQuality.Mythic,
        ammoSpawnAmount:30,
        bullet:{
            def:{
                damage:50,
                radius:0.025,
                range:220,
                falloff:0.7,
                speed:55,
                tracer:tracers.xl,
                obstacleMult:1.5,
            }
        },
        reload:{
            delay:3.3,
            capacity:10,
            shotsPerReload:10,
        },
        recoil:{
            duration:1.37,
            speed:0.65
        },
        speed_mod:0.9,
    },
    {
        idString:"awms",
        fireDelay:1.4,
        spread:0.7,
        lenght:1,
        size:6,
        ammoType:"308sub",
        fireMode:FireMode.Single,
        class:GunClasses.Sniper,
        quality:ItemQuality.Legendary,
        ammoSpawnAmount:25,
        bullet:{
            def:{
                damage:70,
                radius:0.02,
                range:230,
                falloff:0.7,
                speed:38,
                obstacleMult:1.7,
                tracer:tracers.large
            }
        },
        reload:{
            delay:4.5,
            capacity:5,
            shotsPerReload:5,
        },
        recoil:{
            duration:1.45,
            speed:0.25
        },
        speed_mod:0.9,
    },
    {
        idString:"m870",
        fireDelay:0.8,
        spread:6,
        lenght:0.7,
        ammoType:"12g",
        ammoSpawnAmount:10,
        jitterRadius:0.27,
        size:4.3,
        fireMode:FireMode.Single,
        class:GunClasses.Shotgun,
        quality:ItemQuality.Rare,
        bullet:{
            def:{
                damage:7,
                radius:0.014,
                speed:24,
                range:20,
                falloff:0.8,
                criticalMult:1.2,
                tracer:tracers.small
            },
            count:10
        },
        reload:{
            delay:0.8,
            capacity:5,
            shotsPerReload:1,
        },
        recoil:{
            duration:1,
            speed:0.55
        },
        speed_mod:1,
        gasParticles:GasParticles.shotgun
    },
    {
        idString:"spas12",
        fireDelay:0.7,
        spread:3,
        lenght:1,
        ammoType:"12g",
        ammoSpawnAmount:18,
        jitterRadius:0.13,
        class:GunClasses.Shotgun,
        quality:ItemQuality.Epic,
        size:4.5,
        fireMode:FireMode.Single,
        muzzleFlash:MuzzleFlash.normal,
        bullet:{
            def:{
                damage:5,
                radius:0.012,
                speed:32,
                range:54,
                criticalMult:1.15,
                falloff:0.8,
                tracer:tracers.small
            },
            count:10
        },
        reload:{
            delay:0.6,
            capacity:9,
            shotsPerReload:1,
        },
        recoil:{
            duration:1,
            speed:0.6
        },
        speed_mod:0.95,
        gasParticles:GasParticles.shotgun,
        arms:WeaponsArmRig[0],
        image:{
            position:v2.new(0.4,0.01),
            rotation:0
        },
        caseParticle:{
            position:v2.new(0.6,0.3)
        }
    },
    {
        idString:"hp18",
        fireDelay:0.2,
        switchDelay:0.7,
        spread:11,
        lenght:0.65,
        ammoType:"12g",
        ammoSpawnAmount:15,
        jitterRadius:0.2,
        class:GunClasses.Shotgun,
        quality:ItemQuality.Uncommon,
        size:3.8,
        fireMode:FireMode.Auto,
        bullet:{
            def:{
                damage:1.4,
                radius:0.01,
                speed:25,
                falloff:0.7,
                range:23,
                criticalMult:1.2,
                tracer:tracers.tiny
            },
            count:16
        },
        reload:{
            delay:0.7,
            capacity:5,
            shotsPerReload:1,
        },
        recoil:{
            duration:0.4,
            speed:0.75
        },
        speed_mod:1,
        gasParticles:GasParticles.shotgun
    },
    /*{
        idString:"bomb_staff",
        fireDelay:0.9,
        spread:3,
        lenght:0.7,
        size:3.8,
        ammoType:"mana",
        ammoSpawnAmount:2,
        ammoSpawn:"purple_pills",
        mana_consume:20,
        class:GunClasses.Magic,
        quality:ItemQuality.Legendary,
        fireMode:FireMode.Single,
        projectile:{
            def:"bomb_staff_projectile",
            angular_speed:0,
            speed:11
        },
        recoil:{
            duration:1,
            speed:0.6
        },
        speed_mod:0.97,
    },
    {
        idString:"fireball_staff",
        fireDelay:0.5,
        spread:4,
        lenght:0.7,
        size:3.7,
        ammoType:"mana",
        ammoSpawnAmount:2,
        ammoSpawn:"purple_pills",
        mana_consume:5,
        class:GunClasses.Magic,
        quality:ItemQuality.Mythic,
        fireMode:FireMode.Auto,
        projectile:{
            def:"fireball_projectile",
            angular_speed:0,
            speed:14
        },
        recoil:{
            duration:0.6,
            speed:0.8
        },
        speed_mod:0.97,
    },*/
)