import { Definitions,Definition } from "../engine/mod.ts"
import { GameItem, InventoryItemType } from "common/scripts/definitions/utils.ts";

export enum AmmoType{
    //Simples
    "12g"=0,
    "762mm",
    "556mm",
    "9mm",
    "22lr",
    //Anothers
    "50cal",
    "308sub",
    "40mm"
}
export const defaultAmmos:Record<AmmoType,string>={
    //Simples
    [AmmoType["12g"]]:"12g",
    [AmmoType["762mm"]]:"762mm",
    [AmmoType["556mm"]]:"556mm",
    [AmmoType["9mm"]]:"9mm",
    [AmmoType["22lr"]]:"22lr",
    //Anothers
    [AmmoType["50cal"]]:"50cal",
    [AmmoType["308sub"]]:"308sub",
    [AmmoType["40mm"]]:"40mm",
}
export interface AmmoDef extends Definition{
    size:number
    tint:number
    defaultTrail:number
    strongTrail:number
    ammoType:AmmoType
}
export const Ammos=new Definitions<AmmoDef,GameItem>((i)=>{
    i.item_type=InventoryItemType.ammo
})
Ammos.insert(
    //Normals
    {
        idString:"12g",
        ammoType:AmmoType["12g"],
        defaultTrail:0xeeebec,
        strongTrail:0xdb2218,
        tint:0xff0000,
        size:0.01,
    },
    {
        idString:"762mm",
        ammoType:AmmoType["762mm"],
        defaultTrail:0x6688ff,
        strongTrail:0x0034f2,
        tint:0x0000ff,
        size:0.0029,
    },
    {
        idString:"556mm",
        ammoType:AmmoType["556mm"],
        defaultTrail:0x66ff88,
        strongTrail:0x00a41c,
        tint:0x00ff00,
        size:0.0029,
    },
    {
        idString:"9mm",
        ammoType:AmmoType["9mm"],
        defaultTrail:0xefef9f,
        strongTrail:0xefef33,
        tint:0xffff00,
        size:0.0015,
    },
    {
        idString:"22lr",
        ammoType:AmmoType["22lr"],
        defaultTrail:0xefefef,
        strongTrail:0xefefff,
        tint:0xffffff,
        size:0.001,
    },
    //Anothers
    {
        idString:"50cal",
        ammoType:AmmoType["50cal"],
        defaultTrail:0x555555,
        strongTrail:0x000000,
        tint:0x000000,
        size:0.013,
    },
    {
        idString:"308sub",
        ammoType:AmmoType["308sub"],
        defaultTrail:0x222835,
        strongTrail:0x0c1420,
        tint:0x001330,
        size:0.08,
    },
    {
        idString:"40mm",
        ammoType:AmmoType["40mm"],
        defaultTrail:0x889fcb,
        strongTrail:0x009fcb,
        tint:0x001330,
        size:0.09,
    }
)