import { Definitions,Definition } from "../engine/mod.ts";
import { AmmoType } from "./ammo.ts";
import { BulletDef, GameItem, InventoryItemType } from "./utils.ts";
import { ItemQuality, tracers } from "../others/constants.ts";
export enum FireMode{
    Auto,
    Single
}
export interface GasParticle{
    count:number
}
export enum GunClasses{
    Shotgun,
    Sniper,
    Automatic,
    SMG,
    Magic
}
export interface GunDef extends Definition{
    bullet?:{
        def:BulletDef
        count?:number
    }
    projectile?:{
        def:string
        count?:number
        angular_speed?:number
        speed?:number
    }
    mana_consume?:number
    ammoSpawnAmount?:number
    ammoSpawn?:string
    fireDelay:number
    spread?:number
    lenght:number
    jitterRadius?:number
    fireMode?:FireMode
    speedMult?:number
    size:number
    ammoType:AmmoType
    class:GunClasses
    quality:ItemQuality
    reload?:{
        capacity:number
        delay:number
        shotsPerReload?:number
    }
    recoil?:{
        duration:number
        speed:number
    }
    gasParticles?:GasParticle
}

export const Guns=new Definitions<GunDef,GameItem>((g)=>{
    g.item_type=InventoryItemType.gun
})

export const GasParticles={
    shotgun:{
        count:5
    } satisfies GasParticle,
    automatic:{
        count:1
    } satisfies GasParticle
}

Guns.insert(
    {
        idString:"ak47",
        fireDelay:0.1,
        spread:5,
        lenght:0.7,
        size:4,
        ammoType:AmmoType["762mm"],
        ammoSpawnAmount:90,
        class:GunClasses.Automatic,
        quality:ItemQuality.Uncommon,
        bullet:{
            def:{
                damage:10,
                radius:0.014,
                range:85,
                speed:21,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:2,
            capacity:30
        },
        recoil:{
            duration:0.12,
            speed:0.75
        },
        speedMult:0.97,
        gasParticles:GasParticles.automatic
    },
    {
        idString:"ar15",
        fireDelay:0.12,
        spread:2,
        lenght:0.7,
        size:4,
        ammoType:AmmoType["556mm"],
        ammoSpawnAmount:90,
        class:GunClasses.Automatic,
        quality:ItemQuality.Uncommon,
        bullet:{
            def:{
                damage:9.8,
                radius:0.014,
                range:85,
                speed:24,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:2.2,
            capacity:30
        },
        recoil:{
            duration:0.14,
            speed:0.75
        },
        speedMult:0.95,
        gasParticles:GasParticles.automatic
    },
    {
        idString:"mp5",
        fireDelay:0.09,
        spread:3,
        lenght:0.7,
        size:4,
        ammoType:AmmoType["9mm"],
        ammoSpawnAmount:96,
        class:GunClasses.Automatic,
        quality:ItemQuality.Uncommon,
        bullet:{
            def:{
                damage:8,
                radius:0.014,
                range:85,
                speed:24,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:2,
            capacity:32
        },
        recoil:{
            duration:0.11,
            speed:0.8
        },
        speedMult:1,
        gasParticles:GasParticles.automatic
    },
    {
        idString:"vector",
        fireDelay:0.03,
        spread:1,
        lenght:0.68,
        size:4,
        ammoType:AmmoType["9mm"],
        ammoSpawnAmount:96,
        class:GunClasses.Automatic,
        quality:ItemQuality.Epic,
        bullet:{
            def:{
                damage:4,
                radius:0.014,
                range:35,
                speed:21,
                tracer:tracers.medium
            }
        },
        reload:{
            delay:1.7,
            capacity:33
        },
        recoil:{
            duration:0.07,
            speed:0.77
        },
        speedMult:1,
        gasParticles:GasParticles.automatic
    },
    {
        idString:"kar98k",
        fireDelay:1.2,
        spread:1,
        lenght:0.8,
        size:4.5,
        ammoType:AmmoType["762mm"],
        ammoSpawnAmount:20,
        class:GunClasses.Sniper,
        quality:ItemQuality.Epic,
        bullet:{
            def:{
                damage:44,
                radius:0.02,
                range:85,
                speed:32,
                tracer:tracers.large
            }
        },
        reload:{
            delay:0.9,
            capacity:5,
            shotsPerReload:1,
        },
        recoil:{
            duration:1.25,
            speed:0.4
        },
        speedMult:0.95,
    },
    {
        idString:"awp",
        fireDelay:1.3,
        spread:1.1,
        lenght:0.9,
        size:6,
        ammoType:AmmoType["762mm"],
        class:GunClasses.Sniper,
        quality:ItemQuality.Epic,
        ammoSpawnAmount:30,
        bullet:{
            def:{
                damage:50,
                radius:0.025,
                range:88,
                speed:35,
                tracer:tracers.xl,
                obstacleMult:1.5,
            }
        },
        reload:{
            delay:3.3,
            capacity:10,
            shotsPerReload:10,
        },
        recoil:{
            duration:1.37,
            speed:0.6
        },
        speedMult:0.9,
    },
    {
        idString:"awms",
        fireDelay:1.4,
        spread:1.2,
        lenght:1,
        size:6,
        ammoType:AmmoType["308sub"],
        class:GunClasses.Sniper,
        quality:ItemQuality.Legendary,
        ammoSpawnAmount:25,
        bullet:{
            def:{
                damage:70,
                radius:0.02,
                range:90,
                speed:33,
                obstacleMult:1.7,
                tracer:tracers.large
            }
        },
        reload:{
            delay:5.5,
            capacity:5,
            shotsPerReload:5,
        },
        recoil:{
            duration:1.45,
            speed:0.25
        },
        speedMult:0.9,
    },
    {
        idString:"m870",
        fireDelay:1,
        spread:3,
        lenght:0.7,
        ammoType:AmmoType["12g"],
        ammoSpawnAmount:10,
        jitterRadius:0.25,
        size:4.3,
        fireMode:FireMode.Single,
        class:GunClasses.Shotgun,
        quality:ItemQuality.Uncommon,
        bullet:{
            def:{
                damage:7,
                radius:0.014,
                speed:16,
                range:17,
                tracer:tracers.medium
            },
            count:10
        },
        reload:{
            delay:0.8,
            capacity:5,
            shotsPerReload:1,
        },
        recoil:{
            duration:1.1,
            speed:0.55
        },
        speedMult:1,
        gasParticles:GasParticles.shotgun
    },
    {
        idString:"spas12",
        fireDelay:0.9,
        spread:3,
        lenght:0.6,
        ammoType:AmmoType["12g"],
        ammoSpawnAmount:18,
        jitterRadius:0.05,
        class:GunClasses.Shotgun,
        quality:ItemQuality.Rare,
        size:4.5,
        fireMode:FireMode.Single,
        bullet:{
            def:{
                damage:6.3,
                radius:0.012,
                speed:19,
                range:35,
                tracer:tracers.small
            },
            count:10
        },
        reload:{
            delay:0.8,
            capacity:9,
            shotsPerReload:1,
        },
        recoil:{
            duration:1,
            speed:0.6
        },
        speedMult:0.95,
        gasParticles:GasParticles.shotgun
    },
    {
        idString:"hp18",
        fireDelay:0.2,
        spread:9,
        lenght:0.65,
        ammoType:AmmoType["12g"],
        ammoSpawnAmount:15,
        jitterRadius:0.15,
        class:GunClasses.Shotgun,
        quality:ItemQuality.Uncommon,
        size:3.8,
        fireMode:FireMode.Auto,
        bullet:{
            def:{
                damage:1.4,
                radius:0.01,
                speed:15,
                range:18,
                tracer:tracers.tiny
            },
            count:16
        },
        reload:{
            delay:0.7,
            capacity:5,
            shotsPerReload:1,
        },
        recoil:{
            duration:0.4,
            speed:0.75
        },
        speedMult:1,
        gasParticles:GasParticles.shotgun
    },
    {
        idString:"bomb_staff",
        fireDelay:0.9,
        spread:3,
        lenght:0.7,
        size:3.8,
        ammoType:AmmoType["mana"],
        ammoSpawnAmount:2,
        ammoSpawn:"purple_pills",
        mana_consume:20,
        class:GunClasses.Magic,
        quality:ItemQuality.Legendary,
        fireMode:FireMode.Single,
        projectile:{
            def:"bomb_staff_projectile",
            angular_speed:0,
            speed:11
        },
        recoil:{
            duration:1,
            speed:0.6
        },
        speedMult:0.97,
    },
    {
        idString:"fireball_staff",
        fireDelay:0.5,
        spread:4,
        lenght:0.7,
        size:3.7,
        ammoType:AmmoType["mana"],
        ammoSpawnAmount:2,
        ammoSpawn:"purple_pills",
        mana_consume:5,
        class:GunClasses.Magic,
        quality:ItemQuality.Epic,
        fireMode:FireMode.Auto,
        projectile:{
            def:"fireball_projectile",
            angular_speed:0,
            speed:14
        },
        recoil:{
            duration:0.6,
            speed:0.8
        },
        speedMult:0.97,
    },
)